"""ShortCandidateSelectionTask — Long-Short Phase 2B.

Populates ``ctx.short_candidates`` with the bottom-decile of panel-LTR
scores when ``long_short.enabled = true``. No-op when disabled.

The QP solver (``BuildSourceMapTask``) already reads from
``ctx.short_candidates`` if present (Phase 2A wiring). This task fills
that source with bottom-of-rank names.

Selection logic
---------------
1. Read full-universe panel scores from ``ctx._panel_scores_all`` (stashed
   by ``ApplyScoresTask``).
2. Exclude tickers already held long (``ctx.holdings``) — can't be both
   long and short same security.
3. Exclude ETFs from a static blacklist (avoid shorting index funds).
4. Require a backend that explicitly supports short opens, then exclude tickers
   that are missing/flagged non-shortable in `data/alpaca_borrow_status.json`
   (Phase 2B-Alpaca-research 2026-05-14).
5. Take the bottom ``short_decile`` fraction (default 0.10 → bottom 10%).
6. Cap at ``max_shorts`` (default 5) by lowest score.
7. Wrap each in a ``CandidateResult`` with the panel score; negative
   score signals "short" intent.

References
----------
* Grinold-Kahn 1999 §5 — IR = IC × √breadth. Adding shorts doubles
  breadth → IR×√2 ≈ 40% improvement (theoretical).
* López de Prado, AFML 2018 §10 — meta-labeling for bet sizing.

Config (in side config, OFF by default):

    "long_short": {
      "enabled": true,
      "short_decile": 0.10,
      "max_shorts": 5,
      "etf_blacklist": ["SPY", "GLD", "QQQ", "IWM", "DIA"],
      "max_short_pct": 0.05,
      "max_gross_exposure": 1.30
    }

`max_short_pct` and `max_gross_exposure` are consumed by
``ComputeQPConstraintsTask`` — already wired in Phase 2A.
"""
from __future__ import annotations

import logging
import math

from .context import InferenceContext
from .pipeline import Task

log = logging.getLogger("kernel.pipeline.task_short_candidates")


# Default static ETF blacklist (non-individual-equity instruments).
# Override via `long_short.etf_blacklist` in config.
DEFAULT_ETF_BLACKLIST = frozenset({
    "SPY", "GLD", "QQQ", "IWM", "DIA", "TLT", "HYG", "LQD", "VXX",
    "XLF", "XLE", "XLK", "XLV", "XLY", "XLP", "XLI", "XLB", "XLU", "XLRE",
})


def _load_borrow_status(path: str = "data/alpaca_borrow_status.json") -> dict:
    """Load shortable/easy_to_borrow flags fetched from Alpaca live API.

    Fail-closed at the caller: if missing or invalid, returns {} and the task
    refuses to create synthetic short candidates unless the config explicitly
    opts into allowing missing borrow metadata for research.

    Generated by `scripts/fetch_alpaca_borrow_status.py` (see).
    Fields:
        results[ticker] = {
            "shortable": bool, "easy_to_borrow": bool,
            "marginable": bool, "tradable": bool
        }
    """
    from pathlib import Path  # noqa: PLC0415
    import json as _json  # noqa: PLC0415
    p = Path(path)
    if not p.exists():
        return {}
    try:
        return _json.loads(p.read_text()).get("results", {})
    except Exception:
        return {}


def _short_calibrator(ctx: InferenceContext):
    regime_map = getattr(ctx, "_regime_calibrators", None) or {}
    return regime_map.get(getattr(ctx, "regime", None)) or getattr(
        ctx, "_global_calibrator", None
    )


def _stamp_short_block(ctx: InferenceContext, ticker: str, reason: str) -> None:
    blocked = getattr(ctx, "_blocked_by_ticker", None)
    if blocked is None:
        blocked = {}
        ctx._blocked_by_ticker = blocked  # noqa: SLF001
    blocked.setdefault(ticker, f"short_candidate:{reason}")


def _maybe_fill_short_sigma(
    ctx: InferenceContext,
    cand,
    *,
    ticker: str,
) -> str | None:
    sigma = getattr(cand, "sigma", None)
    if sigma is not None and math.isfinite(float(sigma)) and float(sigma) > 0:
        return None
    kelly_cfg = (ctx.config.get("ranking", {}) or {}).get("kelly_sizing", {}) or {}
    if not bool(kelly_cfg.get("use_realized_vol_fallback", False)):
        return "sigma_missing"
    from renquant_pipeline.kernel.panel_pipeline.job_panel_scoring import (  # noqa: PLC0415
        _realized_vol_annualized,
    )
    window = int(kelly_cfg.get("realized_vol_window_days", 60))
    floor = float(kelly_cfg.get("realized_vol_floor", 0.05))
    ceiling = float(kelly_cfg.get("realized_vol_ceiling", 1.50))
    sig = _realized_vol_annualized((getattr(ctx, "ohlcv", {}) or {}).get(ticker), window)
    if sig is None or not math.isfinite(float(sig)) or float(sig) <= 0:
        return "sigma_missing"
    cand.sigma = float(max(floor, min(ceiling, float(sig))))
    return None


def _enrich_short_candidate(
    ctx: InferenceContext,
    cand,
    *,
    raw_panel_score: float,
) -> str | None:
    cal = _short_calibrator(ctx)
    if cal is None:
        return "calibrator_missing"
    from renquant_pipeline.kernel.panel_pipeline.job_panel_scoring import (  # noqa: PLC0415
        _calibrator_expected_return_at_horizon,
        _calibrator_native_horizon_days,
        _qp_mu_horizon_days,
        _rotation_er_horizon_days,
    )
    native_horizon = _calibrator_native_horizon_days(cal, ctx)
    er_horizon = _rotation_er_horizon_days(ctx, cal)
    mu_horizon = _qp_mu_horizon_days(ctx, cal)
    try:
        prob = float(cal.calibrate_probability(raw_panel_score))
        er = float(_calibrator_expected_return_at_horizon(
            cal, raw_panel_score, er_horizon, native_horizon,
        ))
        mu = float(_calibrator_expected_return_at_horizon(
            cal, raw_panel_score, mu_horizon, native_horizon,
        ))
    except Exception as exc:
        return f"calibration_failed:{type(exc).__name__}"
    if not math.isfinite(er) or er >= 0.0:
        return "expected_return_nonnegative"
    if not math.isfinite(mu) or mu >= 0.0:
        return "mu_nonnegative"
    cand.rank_score = prob
    cand.expected_return = er
    cand.expected_return_horizon_days = er_horizon
    cand.mu = mu
    cand.mu_horizon_days = mu_horizon
    return _maybe_fill_short_sigma(ctx, cand, ticker=cand.ticker)


class ShortCandidateSelectionTask(Task):
    """Phase 2B: pick bottom-decile of panel scores as short candidates.

    No-op when ``long_short.enabled`` is false (default).
    """

    name = "ShortCandidateSelectionTask"

    def run(self, ctx: InferenceContext) -> bool | None:
        ls_cfg = (getattr(ctx, "config", None) or {}).get("long_short", {}) or {}
        if not ls_cfg.get("enabled", False):
            ctx.short_candidates = []  # ensure attribute exists
            return None

        if not bool(getattr(ctx, "supports_short_open", False)):
            ctx.short_candidates = []
            counters = getattr(ctx, "counters", None)
            if counters is None:
                counters = {}
                ctx.counters = counters
            counters["short_open_unsupported"] = (
                int(counters.get("short_open_unsupported", 0)) + 1
            )
            log.warning(
                "ShortCandidateSelectionTask: long_short.enabled=true but "
                "backend does not declare supports_short_open; skipping shorts"
            )
            return None

        # BEAR regime — no shorts (defensive). Phase 2A also skips shorts
        # at the QP constraint layer for BEAR, but we short-circuit here
        # to save the work too.
        if getattr(ctx, "bear_only", False):
            ctx.short_candidates = []
            log.info("ShortCandidateSelectionTask: BEAR mode → no shorts")
            return None

        scores = getattr(ctx, "_panel_scores_all", None)
        if scores is None or len(scores) == 0:
            log.warning(
                "ShortCandidateSelectionTask: ctx._panel_scores_all "
                "missing — was ApplyScoresTask run? Skipping shorts."
            )
            ctx.short_candidates = []
            return None

        # Exclusion sets — only ACTIVELY HELD tickers (overlap with long
        # candidate pool is OK; `BuildSourceMapTask` precedence guarantees
        # the long candidate wins when a ticker is in both sets).
        # Pre-fix this also excluded ctx.candidates (the broad admission
        # pool of 60-70 tickers), leaving the eligible set empty in 2026-05-14
        # smoke. The intent was "don't short tickers we're about to buy long" —
        # but ctx.candidates ⊃ {actual longs}, so excluding the whole pool
        # over-filters. The QP's source-map merging already handles overlap.
        held_tickers = set((ctx.holdings or {}).keys())
        blacklist = frozenset(
            ls_cfg.get("etf_blacklist", DEFAULT_ETF_BLACKLIST)
        )

        # Filter and sort ascending (lowest panel score first)
        eligible = scores.dropna().sort_values(ascending=True)
        eligible = eligible[~eligible.index.isin(held_tickers)]
        eligible = eligible[~eligible.index.isin(blacklist)]

        borrow_status = _load_borrow_status(
            ls_cfg.get("borrow_status_path", "data/alpaca_borrow_status.json")
        )
        if not borrow_status and not bool(ls_cfg.get("allow_missing_borrow_status", False)):
            ctx.short_candidates = []
            counters = getattr(ctx, "counters", None)
            if counters is None:
                counters = {}
                ctx.counters = counters
            counters["short_borrow_status_missing"] = (
                int(counters.get("short_borrow_status_missing", 0)) + 1
            )
            log.warning(
                "ShortCandidateSelectionTask: borrow status missing/invalid; "
                "skipping shorts instead of assuming names are shortable"
            )
            return None

        if borrow_status:
            missing_status = set(eligible.index) - set(borrow_status.keys())
            non_shortable = {
                t for t, info in borrow_status.items()
                if not isinstance(info, dict) or info.get("shortable") is not True
            }
            blocked_for_borrow = missing_status | non_shortable
            if blocked_for_borrow:
                pre_n = len(eligible)
                eligible = eligible[~eligible.index.isin(blocked_for_borrow)]
                if len(eligible) < pre_n:
                    log.info(
                        "ShortCandidateSelectionTask: filtered %d tickers with "
                        "missing/non-shortable borrow status",
                        pre_n - len(eligible),
                    )

        if len(eligible) == 0:
            ctx.short_candidates = []
            log.info("ShortCandidateSelectionTask: 0 eligible after filters")
            return None

        # Take bottom decile, capped at max_shorts
        short_decile = float(ls_cfg.get("short_decile", 0.10))
        max_shorts = int(ls_cfg.get("max_shorts", 5))
        n_bottom = max(1, int(len(eligible) * short_decile))
        n_picked = min(n_bottom, max_shorts)
        picks = eligible.head(n_picked)

        # Wrap in CandidateResult objects and fail closed unless the same
        # calibrated alpha contract used by longs says the bottom-score name
        # has negative edge. QP optimizes μ/Σ; raw rank scores are not μ.
        from renquant_pipeline.kernel.selection import CandidateResult  # noqa: PLC0415
        ctx.short_candidates = []
        for t, v in picks.items():
            raw_score = float(v)
            cand = CandidateResult(
                ticker=t,
                raw_score=raw_score,
                rank_score=float("nan"),
                rs_score=0.0,
                detail=f"short_candidate raw_panel_score={raw_score:.4f}",
                panel_score=raw_score,
            )
            cand.trace_role = "short_candidate"
            block = _enrich_short_candidate(
                ctx,
                cand,
                raw_panel_score=raw_score,
            )
            if block:
                _stamp_short_block(ctx, t, block)
                continue
            ctx.short_candidates.append(cand)
        log.info(
            "ShortCandidateSelectionTask: %d short candidates picked "
            "(bottom %.0f%%, max_shorts=%d) — tickers=%s",
            len(ctx.short_candidates), short_decile * 100, max_shorts,
            [c.ticker for c in ctx.short_candidates],
        )


__all__ = ["ShortCandidateSelectionTask", "DEFAULT_ETF_BLACKLIST"]
