"""Deterministic fixture bars for the D6 default-mode byte-identity pin.

``tests/fixtures/ab_replay_default_evidence.json`` was generated by running
``run_replay`` over exactly these bars on the PRE-D6-conventions code
(origin/main @ f6e818c, before the opt-in stateful/tax/integer/sector
conventions landed). The regression test
``tests/test_replay_d6_conventions.py::TestDefaultModeUnchanged`` re-runs
``run_replay`` over the same bars with NO conventions engaged and asserts the
serialized evidence JSON is byte-identical to the pinned artifact — proving
the opt-in kwargs/flags preserve default behavior exactly, so existing
committed evidence stays reproducible.

Regenerate (ONLY when intentionally re-pinning against a new baseline):

    PYTHONPATH=src python tests/fixtures/d6_default_bars.py

Everything here must stay deterministic: seeded RNG, closed-form
allocators only (no QP solver), fixed pbo_rng_seed default.
"""
from __future__ import annotations

import numpy as np

from renquant_pipeline.kernel.portfolio_qp.allocator_replay import AllocatorReplayBar
from renquant_pipeline.kernel.portfolio_qp.constraint_snapshot import ConstraintSnapshot

FIXTURE_ALLOCATORS = (
    "equal_weight_top_k",
    "inverse_vol_top_k",
    "fractional_kelly_top_k",
)
FIXTURE_INCUMBENT = "equal_weight_top_k"
FIXTURE_PBO_N_SLICES = 8

_TICKERS = ("AAA", "BBB", "CCC", "DDD")
# Two sectors so the sector-cap constraint family is populated and
# constraint_fidelity.decision_grade is exercised in the pinned payload.
_SECTOR_INDICATOR = np.array(
    [
        [1.0, 1.0, 0.0, 0.0],  # Tech: AAA, BBB
        [0.0, 0.0, 1.0, 1.0],  # Energy: CCC, DDD
    ]
)
_SECTOR_CAP_VEC = np.array([0.60, 0.60])
_SECTOR_NAMES = ("Tech", "Energy")


def _snapshot(regime: str) -> ConstraintSnapshot:
    n = len(_TICKERS)
    return ConstraintSnapshot(
        n=n,
        tickers=_TICKERS,
        w_current=np.zeros(n),
        w_upper_hard=np.full(n, 0.40),
        w_upper=np.full(n, 0.40),
        w_lower=0.0,
        dw_max=np.full(n, 1.0),
        cash_reserve=0.05,
        turnover_max=None,
        drawdown=0.0,
        drawdown_limit=0.20,
        gross_max=None,
        wash_sale_mask=np.zeros(n, dtype=bool),
        sector_indicator=_SECTOR_INDICATOR,
        sector_cap_vec=_SECTOR_CAP_VEC,
        sector_names=_SECTOR_NAMES,
        regime=regime,
    )


def build_default_fixture_bars() -> list[AllocatorReplayBar]:
    """40 deterministic bars, 4 names, mixed regimes, 5 bp/side cost."""
    rng = np.random.default_rng(20260709)
    bars: list[AllocatorReplayBar] = []
    for i in range(40):
        regime = "BULL_CALM" if (i // 10) % 2 == 0 else "BULL_VOLATILE"
        if i in (7, 23):
            # All-negative mu bars exercise the no_candidates path.
            mu = rng.uniform(-0.05, -0.01, 4)
        else:
            mu = rng.uniform(-0.01, 0.05, 4)
        bars.append(
            AllocatorReplayBar(
                bar_date=f"2026-{1 + i // 28:02d}-{1 + i % 28:02d}",
                snap=_snapshot(regime),
                mu=mu,
                sigma=rng.uniform(0.10, 0.30, 4),
                fwd_return=rng.normal(0.0005, 0.01, 4),
                regime=regime,
                cost_per_trade_bps=5.0,
            )
        )
    return bars


def _main() -> None:
    import json
    from pathlib import Path

    from renquant_pipeline.kernel.portfolio_qp.run_ab_replay import run_replay

    payload = run_replay(
        build_default_fixture_bars(),
        list(FIXTURE_ALLOCATORS),
        incumbent=FIXTURE_INCUMBENT,
        pbo_n_slices=FIXTURE_PBO_N_SLICES,
    )
    out = Path(__file__).parent / "ab_replay_default_evidence.json"
    out.write_text(json.dumps(payload, indent=2, sort_keys=True))
    print(f"wrote {out}")


if __name__ == "__main__":
    _main()
